# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from src.jarvis_proto import jarvis_tts_pb2 as src_dot_jarvis__proto_dot_jarvis__tts__pb2


class JarvisTTSStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Synthesize = channel.unary_unary(
        '/nvidia.jarvis.tts.JarvisTTS/Synthesize',
        request_serializer=src_dot_jarvis__proto_dot_jarvis__tts__pb2.SynthesizeSpeechRequest.SerializeToString,
        response_deserializer=src_dot_jarvis__proto_dot_jarvis__tts__pb2.SynthesizeSpeechResponse.FromString,
        )
    self.SynthesizeOnline = channel.unary_stream(
        '/nvidia.jarvis.tts.JarvisTTS/SynthesizeOnline',
        request_serializer=src_dot_jarvis__proto_dot_jarvis__tts__pb2.SynthesizeSpeechRequest.SerializeToString,
        response_deserializer=src_dot_jarvis__proto_dot_jarvis__tts__pb2.SynthesizeSpeechResponse.FromString,
        )


class JarvisTTSServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Synthesize(self, request, context):
    """Used to request speech-to-text from the service. Submit a request containing the
    desired text and configuration, and receive audio bytes in the requested format.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SynthesizeOnline(self, request, context):
    """Used to request speech-to-text returned via stream as it becomes available.
    Submit a SynthesizeSpeechRequest with desired text and configuration,
    and receive stream of bytes in the requested format.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_JarvisTTSServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Synthesize': grpc.unary_unary_rpc_method_handler(
          servicer.Synthesize,
          request_deserializer=src_dot_jarvis__proto_dot_jarvis__tts__pb2.SynthesizeSpeechRequest.FromString,
          response_serializer=src_dot_jarvis__proto_dot_jarvis__tts__pb2.SynthesizeSpeechResponse.SerializeToString,
      ),
      'SynthesizeOnline': grpc.unary_stream_rpc_method_handler(
          servicer.SynthesizeOnline,
          request_deserializer=src_dot_jarvis__proto_dot_jarvis__tts__pb2.SynthesizeSpeechRequest.FromString,
          response_serializer=src_dot_jarvis__proto_dot_jarvis__tts__pb2.SynthesizeSpeechResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'nvidia.jarvis.tts.JarvisTTS', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
