# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/jarvis_proto/jarvis_nlp_core.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/jarvis_proto/jarvis_nlp_core.proto',
  package='nvidia.jarvis.nlp',
  syntax='proto3',
  serialized_options=_b('\370\001\001'),
  serialized_pb=_b('\n&src/jarvis_proto/jarvis_nlp_core.proto\x12\x11nvidia.jarvis.nlp\"$\n\x0eNLPModelParams\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"e\n\x14TextTransformRequest\x12\x0c\n\x04text\x18\x01 \x03(\t\x12\r\n\x05top_n\x18\x02 \x01(\r\x12\x30\n\x05model\x18\x03 \x01(\x0b\x32!.nvidia.jarvis.nlp.NLPModelParams\"%\n\x15TextTransformResponse\x12\x0c\n\x04text\x18\x01 \x03(\t\"a\n\x10TextClassRequest\x12\x0c\n\x04text\x18\x01 \x03(\t\x12\r\n\x05top_n\x18\x02 \x01(\r\x12\x30\n\x05model\x18\x03 \x01(\x0b\x32!.nvidia.jarvis.nlp.NLPModelParams\"3\n\x0e\x43lassification\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\"I\n\x14\x43lassificationResult\x12\x31\n\x06labels\x18\x01 \x03(\x0b\x32!.nvidia.jarvis.nlp.Classification\"M\n\x11TextClassResponse\x12\x38\n\x07results\x18\x01 \x03(\x0b\x32\'.nvidia.jarvis.nlp.ClassificationResult\"b\n\x11TokenClassRequest\x12\x0c\n\x04text\x18\x01 \x03(\t\x12\r\n\x05top_n\x18\x03 \x01(\r\x12\x30\n\x05model\x18\x04 \x01(\x0b\x32!.nvidia.jarvis.nlp.NLPModelParams\"R\n\x0fTokenClassValue\x12\r\n\x05token\x18\x01 \x01(\t\x12\x30\n\x05label\x18\x02 \x03(\x0b\x32!.nvidia.jarvis.nlp.Classification\"I\n\x12TokenClassSequence\x12\x33\n\x07results\x18\x01 \x03(\x0b\x32\".nvidia.jarvis.nlp.TokenClassValue\"L\n\x12TokenClassResponse\x12\x36\n\x07results\x18\x01 \x03(\x0b\x32%.nvidia.jarvis.nlp.TokenClassSequence2\xb3\x02\n\rJarvisCoreNLP\x12[\n\x0c\x43lassifyText\x12#.nvidia.jarvis.nlp.TextClassRequest\x1a$.nvidia.jarvis.nlp.TextClassResponse\"\x00\x12_\n\x0e\x43lassifyTokens\x12$.nvidia.jarvis.nlp.TokenClassRequest\x1a%.nvidia.jarvis.nlp.TokenClassResponse\"\x00\x12\x64\n\rTransformText\x12\'.nvidia.jarvis.nlp.TextTransformRequest\x1a(.nvidia.jarvis.nlp.TextTransformResponse\"\x00\x42\x03\xf8\x01\x01\x62\x06proto3')
)




_NLPMODELPARAMS = _descriptor.Descriptor(
  name='NLPModelParams',
  full_name='nvidia.jarvis.nlp.NLPModelParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_name', full_name='nvidia.jarvis.nlp.NLPModelParams.model_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=97,
)


_TEXTTRANSFORMREQUEST = _descriptor.Descriptor(
  name='TextTransformRequest',
  full_name='nvidia.jarvis.nlp.TextTransformRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='nvidia.jarvis.nlp.TextTransformRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='top_n', full_name='nvidia.jarvis.nlp.TextTransformRequest.top_n', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='nvidia.jarvis.nlp.TextTransformRequest.model', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=200,
)


_TEXTTRANSFORMRESPONSE = _descriptor.Descriptor(
  name='TextTransformResponse',
  full_name='nvidia.jarvis.nlp.TextTransformResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='nvidia.jarvis.nlp.TextTransformResponse.text', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=239,
)


_TEXTCLASSREQUEST = _descriptor.Descriptor(
  name='TextClassRequest',
  full_name='nvidia.jarvis.nlp.TextClassRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='nvidia.jarvis.nlp.TextClassRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='top_n', full_name='nvidia.jarvis.nlp.TextClassRequest.top_n', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='nvidia.jarvis.nlp.TextClassRequest.model', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=338,
)


_CLASSIFICATION = _descriptor.Descriptor(
  name='Classification',
  full_name='nvidia.jarvis.nlp.Classification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='class_name', full_name='nvidia.jarvis.nlp.Classification.class_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='nvidia.jarvis.nlp.Classification.score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=391,
)


_CLASSIFICATIONRESULT = _descriptor.Descriptor(
  name='ClassificationResult',
  full_name='nvidia.jarvis.nlp.ClassificationResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='labels', full_name='nvidia.jarvis.nlp.ClassificationResult.labels', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=466,
)


_TEXTCLASSRESPONSE = _descriptor.Descriptor(
  name='TextClassResponse',
  full_name='nvidia.jarvis.nlp.TextClassResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='nvidia.jarvis.nlp.TextClassResponse.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=468,
  serialized_end=545,
)


_TOKENCLASSREQUEST = _descriptor.Descriptor(
  name='TokenClassRequest',
  full_name='nvidia.jarvis.nlp.TokenClassRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='nvidia.jarvis.nlp.TokenClassRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='top_n', full_name='nvidia.jarvis.nlp.TokenClassRequest.top_n', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='nvidia.jarvis.nlp.TokenClassRequest.model', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=547,
  serialized_end=645,
)


_TOKENCLASSVALUE = _descriptor.Descriptor(
  name='TokenClassValue',
  full_name='nvidia.jarvis.nlp.TokenClassValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='nvidia.jarvis.nlp.TokenClassValue.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='nvidia.jarvis.nlp.TokenClassValue.label', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=647,
  serialized_end=729,
)


_TOKENCLASSSEQUENCE = _descriptor.Descriptor(
  name='TokenClassSequence',
  full_name='nvidia.jarvis.nlp.TokenClassSequence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='nvidia.jarvis.nlp.TokenClassSequence.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=731,
  serialized_end=804,
)


_TOKENCLASSRESPONSE = _descriptor.Descriptor(
  name='TokenClassResponse',
  full_name='nvidia.jarvis.nlp.TokenClassResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='nvidia.jarvis.nlp.TokenClassResponse.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=806,
  serialized_end=882,
)

_TEXTTRANSFORMREQUEST.fields_by_name['model'].message_type = _NLPMODELPARAMS
_TEXTCLASSREQUEST.fields_by_name['model'].message_type = _NLPMODELPARAMS
_CLASSIFICATIONRESULT.fields_by_name['labels'].message_type = _CLASSIFICATION
_TEXTCLASSRESPONSE.fields_by_name['results'].message_type = _CLASSIFICATIONRESULT
_TOKENCLASSREQUEST.fields_by_name['model'].message_type = _NLPMODELPARAMS
_TOKENCLASSVALUE.fields_by_name['label'].message_type = _CLASSIFICATION
_TOKENCLASSSEQUENCE.fields_by_name['results'].message_type = _TOKENCLASSVALUE
_TOKENCLASSRESPONSE.fields_by_name['results'].message_type = _TOKENCLASSSEQUENCE
DESCRIPTOR.message_types_by_name['NLPModelParams'] = _NLPMODELPARAMS
DESCRIPTOR.message_types_by_name['TextTransformRequest'] = _TEXTTRANSFORMREQUEST
DESCRIPTOR.message_types_by_name['TextTransformResponse'] = _TEXTTRANSFORMRESPONSE
DESCRIPTOR.message_types_by_name['TextClassRequest'] = _TEXTCLASSREQUEST
DESCRIPTOR.message_types_by_name['Classification'] = _CLASSIFICATION
DESCRIPTOR.message_types_by_name['ClassificationResult'] = _CLASSIFICATIONRESULT
DESCRIPTOR.message_types_by_name['TextClassResponse'] = _TEXTCLASSRESPONSE
DESCRIPTOR.message_types_by_name['TokenClassRequest'] = _TOKENCLASSREQUEST
DESCRIPTOR.message_types_by_name['TokenClassValue'] = _TOKENCLASSVALUE
DESCRIPTOR.message_types_by_name['TokenClassSequence'] = _TOKENCLASSSEQUENCE
DESCRIPTOR.message_types_by_name['TokenClassResponse'] = _TOKENCLASSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NLPModelParams = _reflection.GeneratedProtocolMessageType('NLPModelParams', (_message.Message,), {
  'DESCRIPTOR' : _NLPMODELPARAMS,
  '__module__' : 'src.jarvis_proto.jarvis_nlp_core_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.jarvis.nlp.NLPModelParams)
  })
_sym_db.RegisterMessage(NLPModelParams)

TextTransformRequest = _reflection.GeneratedProtocolMessageType('TextTransformRequest', (_message.Message,), {
  'DESCRIPTOR' : _TEXTTRANSFORMREQUEST,
  '__module__' : 'src.jarvis_proto.jarvis_nlp_core_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.jarvis.nlp.TextTransformRequest)
  })
_sym_db.RegisterMessage(TextTransformRequest)

TextTransformResponse = _reflection.GeneratedProtocolMessageType('TextTransformResponse', (_message.Message,), {
  'DESCRIPTOR' : _TEXTTRANSFORMRESPONSE,
  '__module__' : 'src.jarvis_proto.jarvis_nlp_core_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.jarvis.nlp.TextTransformResponse)
  })
_sym_db.RegisterMessage(TextTransformResponse)

TextClassRequest = _reflection.GeneratedProtocolMessageType('TextClassRequest', (_message.Message,), {
  'DESCRIPTOR' : _TEXTCLASSREQUEST,
  '__module__' : 'src.jarvis_proto.jarvis_nlp_core_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.jarvis.nlp.TextClassRequest)
  })
_sym_db.RegisterMessage(TextClassRequest)

Classification = _reflection.GeneratedProtocolMessageType('Classification', (_message.Message,), {
  'DESCRIPTOR' : _CLASSIFICATION,
  '__module__' : 'src.jarvis_proto.jarvis_nlp_core_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.jarvis.nlp.Classification)
  })
_sym_db.RegisterMessage(Classification)

ClassificationResult = _reflection.GeneratedProtocolMessageType('ClassificationResult', (_message.Message,), {
  'DESCRIPTOR' : _CLASSIFICATIONRESULT,
  '__module__' : 'src.jarvis_proto.jarvis_nlp_core_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.jarvis.nlp.ClassificationResult)
  })
_sym_db.RegisterMessage(ClassificationResult)

TextClassResponse = _reflection.GeneratedProtocolMessageType('TextClassResponse', (_message.Message,), {
  'DESCRIPTOR' : _TEXTCLASSRESPONSE,
  '__module__' : 'src.jarvis_proto.jarvis_nlp_core_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.jarvis.nlp.TextClassResponse)
  })
_sym_db.RegisterMessage(TextClassResponse)

TokenClassRequest = _reflection.GeneratedProtocolMessageType('TokenClassRequest', (_message.Message,), {
  'DESCRIPTOR' : _TOKENCLASSREQUEST,
  '__module__' : 'src.jarvis_proto.jarvis_nlp_core_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.jarvis.nlp.TokenClassRequest)
  })
_sym_db.RegisterMessage(TokenClassRequest)

TokenClassValue = _reflection.GeneratedProtocolMessageType('TokenClassValue', (_message.Message,), {
  'DESCRIPTOR' : _TOKENCLASSVALUE,
  '__module__' : 'src.jarvis_proto.jarvis_nlp_core_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.jarvis.nlp.TokenClassValue)
  })
_sym_db.RegisterMessage(TokenClassValue)

TokenClassSequence = _reflection.GeneratedProtocolMessageType('TokenClassSequence', (_message.Message,), {
  'DESCRIPTOR' : _TOKENCLASSSEQUENCE,
  '__module__' : 'src.jarvis_proto.jarvis_nlp_core_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.jarvis.nlp.TokenClassSequence)
  })
_sym_db.RegisterMessage(TokenClassSequence)

TokenClassResponse = _reflection.GeneratedProtocolMessageType('TokenClassResponse', (_message.Message,), {
  'DESCRIPTOR' : _TOKENCLASSRESPONSE,
  '__module__' : 'src.jarvis_proto.jarvis_nlp_core_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.jarvis.nlp.TokenClassResponse)
  })
_sym_db.RegisterMessage(TokenClassResponse)


DESCRIPTOR._options = None

_JARVISCORENLP = _descriptor.ServiceDescriptor(
  name='JarvisCoreNLP',
  full_name='nvidia.jarvis.nlp.JarvisCoreNLP',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=885,
  serialized_end=1192,
  methods=[
  _descriptor.MethodDescriptor(
    name='ClassifyText',
    full_name='nvidia.jarvis.nlp.JarvisCoreNLP.ClassifyText',
    index=0,
    containing_service=None,
    input_type=_TEXTCLASSREQUEST,
    output_type=_TEXTCLASSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ClassifyTokens',
    full_name='nvidia.jarvis.nlp.JarvisCoreNLP.ClassifyTokens',
    index=1,
    containing_service=None,
    input_type=_TOKENCLASSREQUEST,
    output_type=_TOKENCLASSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TransformText',
    full_name='nvidia.jarvis.nlp.JarvisCoreNLP.TransformText',
    index=2,
    containing_service=None,
    input_type=_TEXTTRANSFORMREQUEST,
    output_type=_TEXTTRANSFORMRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_JARVISCORENLP)

DESCRIPTOR.services_by_name['JarvisCoreNLP'] = _JARVISCORENLP

# @@protoc_insertion_point(module_scope)
