# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/jarvis_proto/jarvis_tts.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.jarvis_proto import audio_pb2 as src_dot_jarvis__proto_dot_audio__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/jarvis_proto/jarvis_tts.proto',
  package='nvidia.jarvis.tts',
  syntax='proto3',
  serialized_options=_b('\370\001\001'),
  serialized_pb=_b('\n!src/jarvis_proto/jarvis_tts.proto\x12\x11nvidia.jarvis.tts\x1a\x1csrc/jarvis_proto/audio.proto\"\x9a\x01\n\x17SynthesizeSpeechRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x15\n\rlanguage_code\x18\x02 \x01(\t\x12.\n\x08\x65ncoding\x18\x03 \x01(\x0e\x32\x1c.nvidia.jarvis.AudioEncoding\x12\x16\n\x0esample_rate_hz\x18\x04 \x01(\x05\x12\x12\n\nvoice_name\x18\x05 \x01(\t\")\n\x18SynthesizeSpeechResponse\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x32\xe5\x01\n\tJarvisTTS\x12g\n\nSynthesize\x12*.nvidia.jarvis.tts.SynthesizeSpeechRequest\x1a+.nvidia.jarvis.tts.SynthesizeSpeechResponse\"\x00\x12o\n\x10SynthesizeOnline\x12*.nvidia.jarvis.tts.SynthesizeSpeechRequest\x1a+.nvidia.jarvis.tts.SynthesizeSpeechResponse\"\x00\x30\x01\x42\x03\xf8\x01\x01\x62\x06proto3')
  ,
  dependencies=[src_dot_jarvis__proto_dot_audio__pb2.DESCRIPTOR,])




_SYNTHESIZESPEECHREQUEST = _descriptor.Descriptor(
  name='SynthesizeSpeechRequest',
  full_name='nvidia.jarvis.tts.SynthesizeSpeechRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='nvidia.jarvis.tts.SynthesizeSpeechRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language_code', full_name='nvidia.jarvis.tts.SynthesizeSpeechRequest.language_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encoding', full_name='nvidia.jarvis.tts.SynthesizeSpeechRequest.encoding', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sample_rate_hz', full_name='nvidia.jarvis.tts.SynthesizeSpeechRequest.sample_rate_hz', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='voice_name', full_name='nvidia.jarvis.tts.SynthesizeSpeechRequest.voice_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=241,
)


_SYNTHESIZESPEECHRESPONSE = _descriptor.Descriptor(
  name='SynthesizeSpeechResponse',
  full_name='nvidia.jarvis.tts.SynthesizeSpeechResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='audio', full_name='nvidia.jarvis.tts.SynthesizeSpeechResponse.audio', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=284,
)

_SYNTHESIZESPEECHREQUEST.fields_by_name['encoding'].enum_type = src_dot_jarvis__proto_dot_audio__pb2._AUDIOENCODING
DESCRIPTOR.message_types_by_name['SynthesizeSpeechRequest'] = _SYNTHESIZESPEECHREQUEST
DESCRIPTOR.message_types_by_name['SynthesizeSpeechResponse'] = _SYNTHESIZESPEECHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SynthesizeSpeechRequest = _reflection.GeneratedProtocolMessageType('SynthesizeSpeechRequest', (_message.Message,), {
  'DESCRIPTOR' : _SYNTHESIZESPEECHREQUEST,
  '__module__' : 'src.jarvis_proto.jarvis_tts_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.jarvis.tts.SynthesizeSpeechRequest)
  })
_sym_db.RegisterMessage(SynthesizeSpeechRequest)

SynthesizeSpeechResponse = _reflection.GeneratedProtocolMessageType('SynthesizeSpeechResponse', (_message.Message,), {
  'DESCRIPTOR' : _SYNTHESIZESPEECHRESPONSE,
  '__module__' : 'src.jarvis_proto.jarvis_tts_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.jarvis.tts.SynthesizeSpeechResponse)
  })
_sym_db.RegisterMessage(SynthesizeSpeechResponse)


DESCRIPTOR._options = None

_JARVISTTS = _descriptor.ServiceDescriptor(
  name='JarvisTTS',
  full_name='nvidia.jarvis.tts.JarvisTTS',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=287,
  serialized_end=516,
  methods=[
  _descriptor.MethodDescriptor(
    name='Synthesize',
    full_name='nvidia.jarvis.tts.JarvisTTS.Synthesize',
    index=0,
    containing_service=None,
    input_type=_SYNTHESIZESPEECHREQUEST,
    output_type=_SYNTHESIZESPEECHRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SynthesizeOnline',
    full_name='nvidia.jarvis.tts.JarvisTTS.SynthesizeOnline',
    index=1,
    containing_service=None,
    input_type=_SYNTHESIZESPEECHREQUEST,
    output_type=_SYNTHESIZESPEECHRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_JARVISTTS)

DESCRIPTOR.services_by_name['JarvisTTS'] = _JARVISTTS

# @@protoc_insertion_point(module_scope)
