# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/jarvis_proto/jarvis_nlp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.jarvis_proto import jarvis_nlp_core_pb2 as src_dot_jarvis__proto_dot_jarvis__nlp__core__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/jarvis_proto/jarvis_nlp.proto',
  package='nvidia.jarvis.nlp',
  syntax='proto3',
  serialized_options=_b('\370\001\001'),
  serialized_pb=_b('\n!src/jarvis_proto/jarvis_nlp.proto\x12\x11nvidia.jarvis.nlp\x1a&src/jarvis_proto/jarvis_nlp_core.proto\"\x16\n\x14\x41nalyzeIntentContext\"\x96\x01\n\x14\x41nalyzeIntentOptions\x12\x19\n\x0fprevious_intent\x18\x01 \x01(\tH\x00\x12:\n\x07vectors\x18\x02 \x01(\x0b\x32\'.nvidia.jarvis.nlp.AnalyzeIntentContextH\x00\x12\x0e\n\x06\x64omain\x18\x03 \x01(\t\x12\x0c\n\x04lang\x18\x04 \x01(\tB\t\n\x07\x63ontext\"_\n\x14\x41nalyzeIntentRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x38\n\x07options\x18\x02 \x01(\x0b\x32\'.nvidia.jarvis.nlp.AnalyzeIntentOptions\"\xc4\x01\n\x15\x41nalyzeIntentResponse\x12\x31\n\x06intent\x18\x01 \x01(\x0b\x32!.nvidia.jarvis.nlp.Classification\x12\x31\n\x05slots\x18\x02 \x03(\x0b\x32\".nvidia.jarvis.nlp.TokenClassValue\x12\x12\n\ndomain_str\x18\x03 \x01(\t\x12\x31\n\x06\x64omain\x18\x04 \x01(\x0b\x32!.nvidia.jarvis.nlp.Classification\"&\n\x16\x41nalyzeEntitiesOptions\x12\x0c\n\x04lang\x18\x04 \x01(\t\"c\n\x16\x41nalyzeEntitiesRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12:\n\x07options\x18\x02 \x01(\x0b\x32).nvidia.jarvis.nlp.AnalyzeEntitiesOptions2\xbe\x02\n\tJarvisNLP\x12\x65\n\x0f\x41nalyzeEntities\x12).nvidia.jarvis.nlp.AnalyzeEntitiesRequest\x1a%.nvidia.jarvis.nlp.TokenClassResponse\"\x00\x12\x64\n\rAnalyzeIntent\x12\'.nvidia.jarvis.nlp.AnalyzeIntentRequest\x1a(.nvidia.jarvis.nlp.AnalyzeIntentResponse\"\x00\x12\x64\n\rPunctuateText\x12\'.nvidia.jarvis.nlp.TextTransformRequest\x1a(.nvidia.jarvis.nlp.TextTransformResponse\"\x00\x42\x03\xf8\x01\x01\x62\x06proto3')
  ,
  dependencies=[src_dot_jarvis__proto_dot_jarvis__nlp__core__pb2.DESCRIPTOR,])




_ANALYZEINTENTCONTEXT = _descriptor.Descriptor(
  name='AnalyzeIntentContext',
  full_name='nvidia.jarvis.nlp.AnalyzeIntentContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=118,
)


_ANALYZEINTENTOPTIONS = _descriptor.Descriptor(
  name='AnalyzeIntentOptions',
  full_name='nvidia.jarvis.nlp.AnalyzeIntentOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='previous_intent', full_name='nvidia.jarvis.nlp.AnalyzeIntentOptions.previous_intent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vectors', full_name='nvidia.jarvis.nlp.AnalyzeIntentOptions.vectors', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domain', full_name='nvidia.jarvis.nlp.AnalyzeIntentOptions.domain', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lang', full_name='nvidia.jarvis.nlp.AnalyzeIntentOptions.lang', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='context', full_name='nvidia.jarvis.nlp.AnalyzeIntentOptions.context',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=121,
  serialized_end=271,
)


_ANALYZEINTENTREQUEST = _descriptor.Descriptor(
  name='AnalyzeIntentRequest',
  full_name='nvidia.jarvis.nlp.AnalyzeIntentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='nvidia.jarvis.nlp.AnalyzeIntentRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='options', full_name='nvidia.jarvis.nlp.AnalyzeIntentRequest.options', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=368,
)


_ANALYZEINTENTRESPONSE = _descriptor.Descriptor(
  name='AnalyzeIntentResponse',
  full_name='nvidia.jarvis.nlp.AnalyzeIntentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='intent', full_name='nvidia.jarvis.nlp.AnalyzeIntentResponse.intent', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slots', full_name='nvidia.jarvis.nlp.AnalyzeIntentResponse.slots', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domain_str', full_name='nvidia.jarvis.nlp.AnalyzeIntentResponse.domain_str', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domain', full_name='nvidia.jarvis.nlp.AnalyzeIntentResponse.domain', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=567,
)


_ANALYZEENTITIESOPTIONS = _descriptor.Descriptor(
  name='AnalyzeEntitiesOptions',
  full_name='nvidia.jarvis.nlp.AnalyzeEntitiesOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lang', full_name='nvidia.jarvis.nlp.AnalyzeEntitiesOptions.lang', index=0,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=569,
  serialized_end=607,
)


_ANALYZEENTITIESREQUEST = _descriptor.Descriptor(
  name='AnalyzeEntitiesRequest',
  full_name='nvidia.jarvis.nlp.AnalyzeEntitiesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='nvidia.jarvis.nlp.AnalyzeEntitiesRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='options', full_name='nvidia.jarvis.nlp.AnalyzeEntitiesRequest.options', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=609,
  serialized_end=708,
)

_ANALYZEINTENTOPTIONS.fields_by_name['vectors'].message_type = _ANALYZEINTENTCONTEXT
_ANALYZEINTENTOPTIONS.oneofs_by_name['context'].fields.append(
  _ANALYZEINTENTOPTIONS.fields_by_name['previous_intent'])
_ANALYZEINTENTOPTIONS.fields_by_name['previous_intent'].containing_oneof = _ANALYZEINTENTOPTIONS.oneofs_by_name['context']
_ANALYZEINTENTOPTIONS.oneofs_by_name['context'].fields.append(
  _ANALYZEINTENTOPTIONS.fields_by_name['vectors'])
_ANALYZEINTENTOPTIONS.fields_by_name['vectors'].containing_oneof = _ANALYZEINTENTOPTIONS.oneofs_by_name['context']
_ANALYZEINTENTREQUEST.fields_by_name['options'].message_type = _ANALYZEINTENTOPTIONS
_ANALYZEINTENTRESPONSE.fields_by_name['intent'].message_type = src_dot_jarvis__proto_dot_jarvis__nlp__core__pb2._CLASSIFICATION
_ANALYZEINTENTRESPONSE.fields_by_name['slots'].message_type = src_dot_jarvis__proto_dot_jarvis__nlp__core__pb2._TOKENCLASSVALUE
_ANALYZEINTENTRESPONSE.fields_by_name['domain'].message_type = src_dot_jarvis__proto_dot_jarvis__nlp__core__pb2._CLASSIFICATION
_ANALYZEENTITIESREQUEST.fields_by_name['options'].message_type = _ANALYZEENTITIESOPTIONS
DESCRIPTOR.message_types_by_name['AnalyzeIntentContext'] = _ANALYZEINTENTCONTEXT
DESCRIPTOR.message_types_by_name['AnalyzeIntentOptions'] = _ANALYZEINTENTOPTIONS
DESCRIPTOR.message_types_by_name['AnalyzeIntentRequest'] = _ANALYZEINTENTREQUEST
DESCRIPTOR.message_types_by_name['AnalyzeIntentResponse'] = _ANALYZEINTENTRESPONSE
DESCRIPTOR.message_types_by_name['AnalyzeEntitiesOptions'] = _ANALYZEENTITIESOPTIONS
DESCRIPTOR.message_types_by_name['AnalyzeEntitiesRequest'] = _ANALYZEENTITIESREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnalyzeIntentContext = _reflection.GeneratedProtocolMessageType('AnalyzeIntentContext', (_message.Message,), {
  'DESCRIPTOR' : _ANALYZEINTENTCONTEXT,
  '__module__' : 'src.jarvis_proto.jarvis_nlp_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.jarvis.nlp.AnalyzeIntentContext)
  })
_sym_db.RegisterMessage(AnalyzeIntentContext)

AnalyzeIntentOptions = _reflection.GeneratedProtocolMessageType('AnalyzeIntentOptions', (_message.Message,), {
  'DESCRIPTOR' : _ANALYZEINTENTOPTIONS,
  '__module__' : 'src.jarvis_proto.jarvis_nlp_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.jarvis.nlp.AnalyzeIntentOptions)
  })
_sym_db.RegisterMessage(AnalyzeIntentOptions)

AnalyzeIntentRequest = _reflection.GeneratedProtocolMessageType('AnalyzeIntentRequest', (_message.Message,), {
  'DESCRIPTOR' : _ANALYZEINTENTREQUEST,
  '__module__' : 'src.jarvis_proto.jarvis_nlp_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.jarvis.nlp.AnalyzeIntentRequest)
  })
_sym_db.RegisterMessage(AnalyzeIntentRequest)

AnalyzeIntentResponse = _reflection.GeneratedProtocolMessageType('AnalyzeIntentResponse', (_message.Message,), {
  'DESCRIPTOR' : _ANALYZEINTENTRESPONSE,
  '__module__' : 'src.jarvis_proto.jarvis_nlp_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.jarvis.nlp.AnalyzeIntentResponse)
  })
_sym_db.RegisterMessage(AnalyzeIntentResponse)

AnalyzeEntitiesOptions = _reflection.GeneratedProtocolMessageType('AnalyzeEntitiesOptions', (_message.Message,), {
  'DESCRIPTOR' : _ANALYZEENTITIESOPTIONS,
  '__module__' : 'src.jarvis_proto.jarvis_nlp_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.jarvis.nlp.AnalyzeEntitiesOptions)
  })
_sym_db.RegisterMessage(AnalyzeEntitiesOptions)

AnalyzeEntitiesRequest = _reflection.GeneratedProtocolMessageType('AnalyzeEntitiesRequest', (_message.Message,), {
  'DESCRIPTOR' : _ANALYZEENTITIESREQUEST,
  '__module__' : 'src.jarvis_proto.jarvis_nlp_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.jarvis.nlp.AnalyzeEntitiesRequest)
  })
_sym_db.RegisterMessage(AnalyzeEntitiesRequest)


DESCRIPTOR._options = None

_JARVISNLP = _descriptor.ServiceDescriptor(
  name='JarvisNLP',
  full_name='nvidia.jarvis.nlp.JarvisNLP',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=711,
  serialized_end=1029,
  methods=[
  _descriptor.MethodDescriptor(
    name='AnalyzeEntities',
    full_name='nvidia.jarvis.nlp.JarvisNLP.AnalyzeEntities',
    index=0,
    containing_service=None,
    input_type=_ANALYZEENTITIESREQUEST,
    output_type=src_dot_jarvis__proto_dot_jarvis__nlp__core__pb2._TOKENCLASSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AnalyzeIntent',
    full_name='nvidia.jarvis.nlp.JarvisNLP.AnalyzeIntent',
    index=1,
    containing_service=None,
    input_type=_ANALYZEINTENTREQUEST,
    output_type=_ANALYZEINTENTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PunctuateText',
    full_name='nvidia.jarvis.nlp.JarvisNLP.PunctuateText',
    index=2,
    containing_service=None,
    input_type=src_dot_jarvis__proto_dot_jarvis__nlp__core__pb2._TEXTTRANSFORMREQUEST,
    output_type=src_dot_jarvis__proto_dot_jarvis__nlp__core__pb2._TEXTTRANSFORMRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_JARVISNLP)

DESCRIPTOR.services_by_name['JarvisNLP'] = _JARVISNLP

# @@protoc_insertion_point(module_scope)
